language: php
sudo: false

matrix:
    include:
      - php: 7.0

cache:
    directories:
      - "$HOME/.composer/cache"

before_install:
    - mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d
    - |
        echo "apc.enabled=1
        apc.enable_cli=1
        apc.use_request_time=0
        " > ./apc.ini
    - phpenv config-add ./apc.ini
    - yes '' | pecl install apcu

install:
    - composer update --prefer-dist --prefer-stable

script:
    - ./vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - pip install --user codecov && codecov

notifications:
    email: false
